# Generated by Django 2.2.2 on 2019-06-16 16:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Year', models.IntegerField(default='')),
                ('Rated', models.CharField(blank=True, max_length=50)),
                ('Released', models.CharField(blank=True, max_length=20)),
                ('Runtime', models.CharField(blank=True, max_length=20)),
                ('Genre', models.CharField(blank=True, max_length=100)),
                ('Director', models.CharField(blank=True, max_length=100)),
                ('Writer', models.CharField(blank=True, max_length=10000)),
                ('Actors', models.CharField(blank=True, max_length=1000)),
                ('Plot', models.CharField(blank=True, max_length=10000)),
                ('Language', models.CharField(blank=True, max_length=1000)),
                ('Country', models.CharField(blank=True, max_length=50)),
                ('Awards', models.CharField(blank=True, max_length=1000)),
                ('Poster', models.CharField(blank=True, max_length=1000)),
                ('Metascore', models.CharField(blank=True, max_length=50)),
                ('ImdbRating', models.CharField(blank=True, max_length=50)),
                ('ImdbVotes', models.CharField(blank=True, max_length=100)),
                ('ImdbID', models.CharField(blank=True, max_length=100)),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('DVD', models.CharField(blank=True, max_length=100)),
                ('BoxOffice', models.CharField(blank=True, max_length=100)),
                ('Production', models.CharField(blank=True, max_length=200)),
                ('Website', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=10000)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=50)),
                ('Value', models.CharField(max_length=50)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to='movies.Movie')),
            ],
            options={
                'unique_together': {('Movie', 'Source')},
            },
        ),
    ]
