# Generated by Django 2.2.2 on 2019-06-08 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('Movie', 'Source')},
        ),
    ]
