# Generated by Django 2.2.2 on 2019-06-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190609_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Year',
            field=models.IntegerField(default=''),
        ),
    ]
