# Generated by Django 2.2.2 on 2019-06-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190609_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=10000)),
                ('Movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='movies.Movie')),
            ],
            options={
                'unique_together': {('Movie_id', 'Comment')},
            },
        ),
    ]
