# Generated by Django 2.2.2 on 2019-06-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
