# Generated by Django 2.2.2 on 2019-06-09 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20190609_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
