# Generated by Django 2.2.2 on 2019-06-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20190609_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
