# Generated by Django 2.2.2 on 2019-06-09 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=10000)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='movies.Movie')),
            ],
        ),
    ]
