# Generated by Django 2.2.2 on 2019-06-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_id', models.IntegerField()),
                ('Total_comments', models.IntegerField()),
                ('Place', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
