# Generated by Django 2.2.2 on 2019-06-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_top'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top',
        ),
    ]
