# Generated by Django 2.2.2 on 2019-06-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_delete_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_comments', models.IntegerField()),
                ('Movie_id', models.IntegerField()),
                ('Place', models.IntegerField()),
            ],
        ),
    ]
