# Generated by Django 2.2.2 on 2019-06-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='Place',
        ),
    ]
