# Generated by Django 2.2.2 on 2019-06-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_remove_top_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top',
        ),
    ]
